### ISSUE TITLE
param declaration does not honor java.lang.* types

### ISSUE THREAD

**Issue by maxandersen** [angelozerr/qute-ls#2]
```
{@java.util.List<String> dependencies}
{#for dep in dependencies}
//DEPS {dep}
{/for}
```

fails 

```
{@java.util.List<java.lang.String> dependencies}
{#for dep in dependencies}
//DEPS {dep}
{/for}
```

works.

I believe qute works with both.

**Comment by angelozerr** [comment]
Are you sure that you can do that with qute quarkus support?

**Comment by angelozerr** [comment]
Fixed with https://github.com/angelozerr/qute-ls/commit/443780b568895fd02bfc9a7dadaabafa057117f9

![image](https://user-images.githubusercontent.com/1932211/138647586-92381cb6-8607-49d5-a8e5-4aa0fa5281a8.png)
