### ISSUE TITLE
java.lang.Iterable fails in parameter declaration

### ISSUE THREAD

**Issue by maxandersen** [angelozerr/qute-ls#3]
```
{@java.lang.Iterable dependencies}
{#for dep in dependencies}
//DEPS {dep}
{/for}
```

fails with message that it is not a java.lang.Iterable

**Comment by angelozerr** [comment]
Fixed with https://github.com/angelozerr/qute-ls/commit/443780b568895fd02bfc9a7dadaabafa057117f9

![image](https://user-images.githubusercontent.com/1932211/138647793-363d8db6-c48b-4cc4-9cef-f210664edda4.png)
