### ISSUE TITLE
provide quick fix to declare unknow property

### ISSUE THREAD

**Issue by maxandersen** [angelozerr/qute-ls#6]
i.e.
```
{#for dep in dependencies}
//DEPS {dep}
{/for}
```

complains about it cannot be resolved to a variable.

Would be nice if quickfix available to have it add:

```
{@java.util.List<String> dependencies}
{#for dep in dependencies}
//DEPS {dep}
{/for}
```

list because its in a for loop its being found.

**Comment by maxandersen** [comment]
maybe even make it a java.lang.Iterable as it would work for Set and others too.

**Comment by angelozerr** [comment]
> maybe even make it a java.lang.Iterable as it would work for Set and others too.

I think we can provide several code fixes with List, Set and Iterable (commons usecases). In your sample it should generate `List<String>` why String, why not `List<Object>`?

**Comment by angelozerr** [comment]
I think we should provide too a quick fixes to generate a `#set`

**Comment by maxandersen** [comment]
If its List<Object> we go for it should just be List as they are equivalent imo.

**Comment by angelozerr** [comment]
Here a demo with this quick fix:

![UndefinedVariableCodeActionDemo](https://user-images.githubusercontent.com/1932211/141084071-a87db0fa-3bd6-43b0-b037-983e0b4443fe.gif)
