### ISSUE TITLE
Wrong content type mapping

### ISSUE THREAD

**Issue by jeffmaury** [angelozerr/qute-ls#7]
The LS is bound to files *.qute.html but Qute can be used to generate content other than HTML. Alizer (https://github.com/redhat-developer/alizer) is using it to generate JSON and TEXT output.
I suggest mapping should be *.qute.* or even *qute*

**Comment by angelozerr** [comment]
I define a content type per type (qute.html, qute.txt, qute.yaml, qute.json) https://github.com/angelozerr/qute-ls/blob/669dd2ffeaf6f7662a3d8b55d967ae5951f32381/com.redhat.qute.lsp4e/plugin.xml#L9

Now you should benefit with Qute synatx coloration  inside yaml, txt (json I don't know why it doesn't word, perhaps a bug from TMP4E?)

![image](https://user-images.githubusercontent.com/1932211/138958979-db395fa9-1d02-4472-b25c-7536d1f9b7ec.png)
